-- liquibase formatted sql

-- changeset system:insert-initial-user-roles dbms:mysql

INSERT INTO PATIENT_MANAGEMENT_USER_ROLE (user_id, role_id) 
VALUES((SELECT ID FROM PATIENT_MANAGEMENT_USER WHERE USERNAME = 'admin'), (SELECT ID FROM PATIENT_MANAGEMENT_ROLE WHERE NAME = 'ROLE_MANAGER'));


INSERT INTO PATIENT_MANAGEMENT_USER_ROLE (user_id, role_id) 
VALUES((SELECT ID FROM PATIENT_MANAGEMENT_USER WHERE USERNAME = 'dr_kuldeep'), (SELECT ID FROM PATIENT_MANAGEMENT_ROLE WHERE NAME = 'ROLE_DOCTOR'));

COMMIT;