server:
  port: 9092

spring:
  application:
    name: patient-backend-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/healthdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

management:
  endpoints:
    web:
      exposure:
        include: actuator,health,info,metrics


logging:
  level:
    com.hospitalmanagement.patient: INFO
    org.springframework: DEBUG
    com.hospitalmanagement: DEBUG
    org:
      hibernate:
        boot:
          model:
            naming: DEBUG
security:
  jwt:
    secret: "${JWT_SECRET_KEY:iXew3rva2D5YlryDewkVWpmCZKBf2sgJgfzHIr2bGtk}"
