-- Create PATIENT_MANAGEMENT_ROLE table
CREATE TABLE IF NOT EXISTS PATIENT_MANAGEMENT_ROLE (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(20) NOT NULL UNIQUE,
    description VARCHAR(255) NOT NULL
);

-- Create PATIENT_MANAGEMENT_USER table
CREATE TABLE IF NOT EXISTS PATIENT_MANAGEMENT_USER (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(100) NOT NULL,
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create PATIENT_MANAGEMENT_USER_ROLE junction table for many-to-many relationship
CREATE TABLE IF NOT EXISTS PATIENT_MANAGEMENT_USER_ROLE (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    FOREIGN KEY (user_id) REFERENCES PATIENT_MANAGEMENT_USER(id) ON DELETE CASCADE,
    FOREIGN KEY (role_id) REFERENCES PATIENT_MANAGEMENT_ROLE(id) ON DELETE CASCADE
); 